In [1]:
# nlp_exercise 3

In [6]:
import nltk

nltk.download('punkt')
from nltk.tokenize import word_tokenize

import math

from hazm import *


[nltk_data] Downloading package punkt to

[nltk_data]     C:\Users\MEHR\AppData\Roaming\nltk_data...

[nltk_data]   Package punkt is already up-to-date!


In [7]:
# reading documents

with open('text_1.txt.txt','r', encoding="utf-8") as file:
    doc_s1 = file.read()
    
with open('text_2.txt.txt','r', encoding="utf-8") as file:
    doc_s2 = file.read()
    
with open('text_3.txt.txt','r', encoding="utf-8") as file:
    doc_s3 = file.read()
    
with open('text_4.txt.txt','r', encoding="utf-8") as file:
    doc_s4 = file.read()
    
with open('text_5.txt.txt','r', encoding="utf-8") as file:
    doc_s5 = file.read()

In [4]:
print(doc_s1)

به گزارش "ورزش سه"، رئال مادرید در فصل 22-2021 به شکلی دراماتیک توانست قهرمان چمپیونزلیگ شود. رئال در هر سه مرحله حذفی تا رسیدن به فینال توانست بازی‌های باخته را با برد عوض کند. برابر پی اس جی، چلسی و سیتی رئال چیزی تا حذف فاصله نداشت اما هر بار به بازی برگشت و توانست ورق را برگرداند.



1896532

رئال فصل گذشته در آنفیلد و از دور رفت یک هشتم نهایی لیگ قهرمانان نیز ابتدا دو گل از لیورپول خورد و سپس توانست پنج گل به ثمر برساند.



تونی کروس در توصیف بازگشت‌های رئال گفت: «همه اینها جنبه روانی دارد. با چندین بار انجام آن، اعتماد به نفس تیم افزایش می یابد و تیم آن را باور می‌کند. می دانید که اگر مقاومت کنید، فوتبال به شما گزینه ای برای بازگشت می دهد. این ذهنیت مشترک همه بازیکنان رئال است و هیچ کس اینجا تسلیم نمی شود. هرگز.»





1795380

کروس ادامه داد: «بازگشت همیشه امکان‌پذیر است و رقبا از قبل می دانند که ما همیشه برمی گردیم، حتی اگر چند گل عقب باشیم. تا داور سوت پایان را نزند، ما آنجا آماده برگرداندن نتیجه هستیم. این به خصوص در دو فصل گذشته خیلی محسوس بود. یک گل می‌تواند همه چیز را تغییر

In [10]:
# preprocessing

def preprocessor(doc_s):
    
    # normalizing
    normalizer = Normalizer()
    normalized_doc = normalizer.normalize(doc_s)
    
    # tokenize into words
    tokens = word_tokenize(normalized_doc)
    
    # deleting punctuations & stop words
    
    with open('persian','r', encoding="utf-8") as file:
        stop_words = file.read().split()
        
    my_punct = ['-' , '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '.','/', ':', ';', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`', '{', '|', '}', '~', '»', '«', '“', '”' , '،']

    for token in tokens:
        if token in my_punct or token in stop_words:
            tokens.remove(token)
            
    # pos tagging
    tagger = POSTagger(model='pos_tagger.model')
    tagged_tokens = tagger.tag(tokens)
        
    # lemmatizing
    lemmatizer = Lemmatizer()

    lemmatized_tokens = []
    for token in tagged_tokens:
        lemmatized_token = lemmatizer.lemmatize(token[0])
        lemmatized_tokens.append(lemmatized_token)
        
    return lemmatized_tokens

        
doc1 = preprocessor(doc_s1)
doc2 = preprocessor(doc_s2)
doc3 = preprocessor(doc_s3)
doc4 = preprocessor(doc_s4)
doc5 = preprocessor(doc_s5)

print(doc1)

['گزارش', 'ورزش', 'رئال', 'مادرید', 'فصل', '۲۲', '۲۰۲۱', 'شکل', 'دراماتیک', 'قهرمان', 'چمپیونزلیگ', 'رئال', 'مرحله', 'حذف', 'رسیدن', 'فینال', 'بازی', 'باخته', 'برد', 'عوض', 'پی', 'اس', 'جی', 'چلسی', 'سیتی', 'رئال', 'تا', 'حذف', 'فاصله', 'اما', 'هر', 'بازی', 'برگ', 'ورق', 'برگرداند', '۱۸۹۶۵۳۲', 'رئال', 'فصل', 'آنفیلد', 'دور', 'هشتم', 'نهایی', 'لیگ', 'قهرمان', 'ابتدا', 'گل', 'لیورپول', 'خورد#خور', 'سپس', 'توانست#توان', 'پنج', 'گل', 'ثمر', 'رساند#رسان', 'تون', 'کروس', 'توصیف', 'بازگشت', 'رئال', ':', 'جنبه', 'روان', 'با', 'چندین', 'بار', 'انجام', 'اعتماد', 'نفس', 'تیم', 'افزایش', 'یافت#یاب', 'تیم', 'باور', 'کرد#کن', 'دانست#دان', 'مقاومت', 'فوتبال', 'شما', 'گزینه', 'بازگشت', 'داد#ده', 'ذهنیت', 'مشترک', 'همه', 'بازیکن', 'رئال', 'هیچ\u200cکس', 'تسلیم', '.', '»', '۱۷۹۵۳۸۰', 'کروس', 'ادامه', ':', 'بازگشت', 'امکان\u200cپذیر', 'و', 'رقبا', 'از', 'قبل', 'دانست#دان', 'ما', 'برمی', 'گشت#گرد', 'اگر', 'چند', 'گل', 'بود#باش', '.', 'تا', 'داور', 'سوت', 'پایان', 'زد#زن', '،', 'ما', 'آماده', 'برگرداندن', 

In [6]:
# BAG OF WORDS TECHNIQUE

In [7]:
# STEP 1 : separating unique words

all_docs_words = doc1 + doc2 + doc3 + doc4 + doc5

unique_words = []

for word in all_docs_words:
    if word not in unique_words:
        unique_words.append(word)

unique_words

['گزارش',
 'ورزش',
 'رئال',
 'مادرید',
 'فصل',
 '۲۲',
 '۲۰۲۱',
 'شکل',
 'دراماتیک',
 'قهرمان',
 'چمپیونزلیگ',
 'مرحله',
 'حذف',
 'رسیدن',
 'فینال',
 'بازی',
 'باخته',
 'برد',
 'عوض',
 'پی',
 'اس',
 'جی',
 'چلسی',
 'سیتی',
 'تا',
 'فاصله',
 'اما',
 'هر',
 'برگ',
 'ورق',
 'برگرداند',
 '۱۸۹۶۵۳۲',
 'آنفیلد',
 'دور',
 'هشتم',
 'نهایی',
 'لیگ',
 'ابتدا',
 'گل',
 'لیورپول',
 'خورد#خور',
 'سپس',
 'توانست#توان',
 'پنج',
 'ثمر',
 'رساند#رسان',
 'تون',
 'کروس',
 'توصیف',
 'بازگشت',
 ':',
 'جنبه',
 'روان',
 'با',
 'چندین',
 'بار',
 'انجام',
 'اعتماد',
 'نفس',
 'تیم',
 'افزایش',
 'یافت#یاب',
 'باور',
 'کرد#کن',
 'دانست#دان',
 'مقاومت',
 'فوتبال',
 'شما',
 'گزینه',
 'داد#ده',
 'ذهنیت',
 'مشترک',
 'همه',
 'بازیکن',
 'هیچ\u200cکس',
 'تسلیم',
 '.',
 '»',
 '۱۷۹۵۳۸۰',
 'ادامه',
 'امکان\u200cپذیر',
 'و',
 'رقبا',
 'از',
 'قبل',
 'ما',
 'برمی',
 'گشت#گرد',
 'اگر',
 'چند',
 'بود#باش',
 'داور',
 'سوت',
 'پایان',
 'زد#زن',
 '،',
 'آماده',
 'برگرداندن',
 'نتیجه',
 'این',
 'به',
 'خصوص',
 'دو',
 'خیلی',
 'محسوس

In [8]:
# STEP 2 : vectorization

def vectorize(doc):
    doc_vector = []
    for word in unique_words:
        word_freq = doc.count(word)
        doc_vector.append(word_freq)
    
    return doc_vector



doc1_vector = vectorize(doc1)
doc2_vector = vectorize(doc2)
doc3_vector = vectorize(doc3)
doc4_vector = vectorize(doc4)
doc5_vector = vectorize(doc5)


print(doc1_vector)



[1, 1, 6, 1, 3, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 5, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 3, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 8, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [9]:
# TF_IDF 

In [10]:
# TF_IDF

def tf_idf(words , total_docs):
    
    
    tf_idf = dict([])
    
    for word in words:
        print('word  ', word)
        
        # tf
        word_freq = 0
        for other_word in words:
            if other_word == word:
                word_freq += 1
       # word_freq = words.count(word)
        tf = word_freq  / len(words)
        print(tf)
        
        # idf
        doc_freq = 0
        for the_doc in total_docs:
            if word in the_doc:
                doc_freq += 1
        idf = math.log(5 / doc_freq )
        print(idf)
        
        # tf_idf
        tf_idf[word] = tf * idf
        print(tf_idf[word])
        
    return tf_idf



total_docs = [doc1 , doc2 , doc3 , doc4 , doc5]
words_tf_idf = tf_idf(unique_words , total_docs)

print(words_tf_idf)




word   گزارش

0.0012391573729863693

0.0

0.0

word   ورزش

0.0012391573729863693

0.22314355131420976

0.00027650997684536526

word   رئال

0.0012391573729863693

0.5108256237659907

0.0006329933379999886

word   مادرید

0.0012391573729863693

0.5108256237659907

0.0006329933379999886

word   فصل

0.0012391573729863693

0.0

0.0

word   ۲۲

0.0012391573729863693

1.6094379124341003

0.001994346855556506

word   ۲۰۲۱

0.0012391573729863693

1.6094379124341003

0.001994346855556506

word   شکل

0.0012391573729863693

0.9162907318741551

0.0011354284162009357

word   دراماتیک

0.0012391573729863693

1.6094379124341003

0.001994346855556506

word   قهرمان

0.0012391573729863693

0.22314355131420976

0.00027650997684536526

word   چمپیونزلیگ

0.0012391573729863693

1.6094379124341003

0.001994346855556506

word   مرحله

0.0012391573729863693

1.6094379124341003

0.001994346855556506

word   حذف

0.0012391573729863693

0.9162907318741551

0.0011354284162009357

word   رسیدن

0.0012391573729

In [11]:
# N_GRAMS

In [12]:
# creating a dictionary including 1gram , 2gram & 3gram for every doc


grams_dict = dict([])

for doc_num , doc_s in zip(range(1,6) , [doc_s1 , doc_s2 , doc_s3 , doc_s4 , doc_s5]):
    for n in range(1,4):
        
        key = 'doc' + str(doc_num) + '_' + str(n) + 'gram'
        
        grams_dict[key] = nltk.ngrams(word_tokenize(doc_s) , n)
        
        # coverting n_grams(which are in zip type) to list
        listed_value = []
        for i in grams_dict[key]:
            listed_value.append(i)
            
        grams_dict[key] = listed_value
        
        
print(grams_dict)


{'doc1_1gram': [('به',), ('گزارش',), ('"',), ('ورزش',), ('سه',), ('"',), ('،',), ('رئال',), ('مادرید',), ('در',), ('فصل',), ('22',), ('-',), ('2021',), ('به',), ('شکلی',), ('دراماتیک',), ('توانست',), ('قهرمان',), ('چمپیونزلیگ',), ('شود',), ('.',), ('رئال',), ('در',), ('هر',), ('سه',), ('مرحله',), ('حذفی',), ('تا',), ('رسیدن',), ('به',), ('فینال',), ('توانست',), ('بازی\u200cهای',), ('باخته',), ('را',), ('با',), ('برد',), ('عوض',), ('کند',), ('.',), ('برابر',), ('پی',), ('اس',), ('جی',), ('،',), ('چلسی',), ('و',), ('سیتی',), ('رئال',), ('چیزی',), ('تا',), ('حذف',), ('فاصله',), ('نداشت',), ('اما',), ('هر',), ('بار',), ('به',), ('بازی',), ('برگشت',), ('و',), ('توانست',), ('ورق',), ('را',), ('برگرداند',), ('.',), ('1896532',), ('رئال',), ('فصل',), ('گذشته',), ('در',), ('آنفیلد',), ('و',), ('از',), ('دور',), ('رفت',), ('یک',), ('هشتم',), ('نهایی',), ('لیگ',), ('قهرمانان',), ('نیز',), ('ابتدا',), ('دو',), ('گل',), ('از',), ('لیورپول',), ('خورد',), ('و',), ('سپس',), ('توانست',), ('پنج',), ('گل

In [13]:
# TF_IDF for grams in a dictionary

grams_tf_idf = dict([])

for doc_gram in grams_dict.keys():
    
    print('doc_gram: ',doc_gram)
    
    key = doc_gram + '_tf_idf'
    
    print('key: ',key)
    
    if '1gram' in key :
        total_docs = [grams_dict['doc1_1gram'] , grams_dict['doc2_1gram'] , grams_dict['doc3_1gram'] , grams_dict['doc4_1gram'] , grams_dict['doc5_1gram']]
        
    elif '2gram' in key :
        total_docs = [grams_dict['doc1_2gram'] , grams_dict['doc2_2gram'] , grams_dict['doc3_2gram'] , grams_dict['doc4_2gram'] , grams_dict['doc5_2gram']]
            
    else :
        total_docs = [grams_dict['doc1_3gram'] , grams_dict['doc2_3gram'] , grams_dict['doc3_3gram'] , grams_dict['doc4_3gram'] , grams_dict['doc5_3gram']]
                
    
    print('grams_dict[doc_gram] : ',grams_dict[doc_gram])
    
    grams_tf_idf[key] = tf_idf(grams_dict[doc_gram] , total_docs)
    
    print('grams_tf_idf[key] : ',grams_tf_idf[key])
    
    


doc_gram:  doc1_1gram

key:  doc1_1gram_tf_idf

grams_dict[doc_gram] :  [('به',), ('گزارش',), ('"',), ('ورزش',), ('سه',), ('"',), ('،',), ('رئال',), ('مادرید',), ('در',), ('فصل',), ('22',), ('-',), ('2021',), ('به',), ('شکلی',), ('دراماتیک',), ('توانست',), ('قهرمان',), ('چمپیونزلیگ',), ('شود',), ('.',), ('رئال',), ('در',), ('هر',), ('سه',), ('مرحله',), ('حذفی',), ('تا',), ('رسیدن',), ('به',), ('فینال',), ('توانست',), ('بازی\u200cهای',), ('باخته',), ('را',), ('با',), ('برد',), ('عوض',), ('کند',), ('.',), ('برابر',), ('پی',), ('اس',), ('جی',), ('،',), ('چلسی',), ('و',), ('سیتی',), ('رئال',), ('چیزی',), ('تا',), ('حذف',), ('فاصله',), ('نداشت',), ('اما',), ('هر',), ('بار',), ('به',), ('بازی',), ('برگشت',), ('و',), ('توانست',), ('ورق',), ('را',), ('برگرداند',), ('.',), ('1896532',), ('رئال',), ('فصل',), ('گذشته',), ('در',), ('آنفیلد',), ('و',), ('از',), ('دور',), ('رفت',), ('یک',), ('هشتم',), ('نهایی',), ('لیگ',), ('قهرمانان',), ('نیز',), ('ابتدا',), ('دو',), ('گل',), ('از',), ('لیورپول',),

In [1]:
# one-hot encoding 

from sklearn.preprocessing import OneHotEncoder
import numpy as np

# categories
with open('tags.txt','r', encoding="utf-8") as file:
    tags = file.read().split()

encoder = OneHotEncoder()
encoded_data = encoder.fit_transform(np.array(tags).reshape(-1, 1))
encoded_data = encoded_data.toarray()

print(encoded_data)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]

 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]

 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]

 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]

 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]

 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]

 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]

 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]

 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
